version: '2'

volumes:
  weston:
  wayland:
  x11:

services:
  weston:
    build: ./wayland-weston
    restart: always
    privileged: true
    group_add:
      - input
      - video
    volumes:
      - 'weston:/run/weston'
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
      io.balena.features.kernel-modules: "1"
      io.balena.features.sysfs: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
      XDG_RUNTIME_DIR: "/run/weston"
    devices:
      - /dev/dri/
